# Generated by Django 3.2.5 on 2022-03-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('names',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('ECE', 'ECE'), ('Statistics', 'Statistics'), ('Math', 'Math')], max_length=100, null=True)),
                ('term_offering', models.CharField(max_length=100, null=True)),
                ('campus', models.CharField(max_length=100, null=True)),
                ('modality', models.CharField(max_length=100, null=True)),
                ('course_description', models.TextField(null=True)),
                ('course_website', models.URLField(null=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('prerequisite_concepts', models.CharField(max_length=200, null=True)),
                ('learning_objective', models.TextField(max_length=200, null=True)),
                ('syllabus', models.TextField(null=True)),
                ('credit_hours', models.IntegerField(null=True)),
                ('special_study', models.BooleanField(default=False, null=True)),
                ('cognate_course', models.BooleanField(default=False, null=True)),
                ('concentration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.concentration')),
                ('prerequisite_courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.course')),
            ],
            options={
                'ordering': ('course_number',),
            },
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('C', 'Concentration'), ('Co', 'Cognate'), ('M', 'Mandatory Course')], max_length=100)),
                ('comparator', models.CharField(choices=[('AL', 'At least'), ('AM', 'At most')], max_length=100)),
                ('waivable', models.BooleanField()),
                ('value', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.course')),
            ],
        ),
    ]
