# Generated by Django 3.2.5 on 2022-03-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20220320_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.URLField(blank=True, null=True),
        ),
    ]
