# Generated by Django 4.0.3 on 2022-04-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20220320_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreerequirement',
            options={'ordering': ('id',)},
        ),
    ]
