# Generated by Django 3.2.5 on 2022-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_degreerequirement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ECE', 'Computer Engineering'), ('STAT', 'Statistics'), ('MATH', 'Math'), ('CEE', 'Civil and Environmental Engineering'), ('BIT', 'Business Information Technology'), ('BCHM', 'Biochemistry'), ('AOE', 'Aerospace and Ocean Engineering'), ('ACIS', 'Accounting and Information Systems'), ('ME', 'Mechanical Engineering'), ('PHIL', 'Philosophy'), ('PPWS', 'Plant Pathology, Physiology, & Weed Science'), ('STS', 'Science and Technology Studies'), ('EDRE', 'Educational Research and Evaluation'), ('ESM', 'Engineering Science and Mechanics'), ('GEOG', 'Geography'), ('ISE', 'Industrial Systems Engineering')], max_length=100, null=True),
        ),
    ]
